### ISSUE TITLE
"Module Declares Its Path..." Error on go get

### ISSUE THREAD

**Issue by kalverra** [vakenbolt/go-test-report#11]
Trying to use this tool, I ran into the below issue using `go get`

```
❯ go get -u github.com/vakenbolt/go-test-report/
go get: github.com/vakenbolt/go-test-report@none updating to
	github.com/vakenbolt/go-test-report@v0.0.0-20210215040814-04fb43143217: parsing go.mod:
	module declares its path as: go-test-report
	        but was required as: github.com/vakenbolt/go-test-report
```

**Comment by SergeyBibikov** [comment]
Hey! Same story. Running go v 1.16.2

**Comment by vakenbolt** [comment]
@kalverra @SergeyBibikov Thanks for reporting this. I will take a look at this today and see if I can issue a patch shortly after. Cheers!

**Comment by vakenbolt** [comment]
@kalverra @SergeyBibikov I was able to reproduce the issue on my local machine once I upgrade my local go to 1.16. I patched the `go.mod` file and everything should be working now. Let me know if this resolves the issue for. Have a great day! Cheers! 🍻

**Comment by SergeyBibikov** [comment]
@vakenbolt Hi! Thanks a lot! Works like a charm now!

**Comment by vakenbolt** [comment]
@SergeyBibikov Awesome! Thanks for letting me know 💯

**Comment by vakenbolt** [comment]
The patch for the issue has been verified, closing this issue :)
