### ISSUE TITLE
Speeding up execution time for large go projects

### ISSUE THREAD

**Issue by afbjorklund** [vakenbolt/go-test-report#27]
Currently it takes around 10 seconds, for a project with around 1000 tests.

```
[go-test-report] finished in 11.258970993s
```

This means it takes almost as long to generate report, as to run the tests...

`DONE 924 tests, 2 skipped in 15.500s`

---

Most of the time is spent running `go list -json`

This can be done in parallel (go), or even cached (file).

Parallel: `[go-test-report] finished in 8.929561069s`

Cached: `[go-test-report] finished in 109.123483ms`

**Comment by vakenbolt** [comment]
This is really _really_ cool!! Awesome work and thanks for doing this. The performance benefit as a result of this PR is fantastic! I'll merge this tonight. :beers:
